repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: detect-private-key
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
    -   id: mypy
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
